"""empty message

Revision ID: 08d4c7994c86
Revises: 0b4258c76dd8
Create Date: 2023-12-23 17:12:34.573732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08d4c7994c86'
down_revision = '0b4258c76dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicantresume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_user_resume', sa.LargeBinary(), nullable=True),
    sa.Column('applicant_resume_name', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['postjobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_column('resume_name')
        batch_op.drop_column('user_resume')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_resume', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resume_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    op.drop_table('applicantresume')
    # ### end Alembic commands ###
