"""empty message

Revision ID: 0b4258c76dd8
Revises: 7e93bd850a22
Create Date: 2023-12-23 16:12:03.975606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4258c76dd8'
down_revision = '7e93bd850a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'employer', ['employer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employer_id')

    # ### end Alembic commands ###
