"""empty message

Revision ID: 0c97f8eb75bd
Revises: dfa907ae9105
Create Date: 2024-02-24 03:32:35.946381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c97f8eb75bd'
down_revision = 'dfa907ae9105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.drop_constraint('postjobs_company_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.create_unique_constraint('postjobs_company_email_key', ['company_email'])

    # ### end Alembic commands ###
