"""empty message

Revision ID: 2c3857705504
Revises: 5113c2288e39
Create Date: 2023-12-29 17:50:20.133209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3857705504'
down_revision = '5113c2288e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('current_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.drop_column('current_time')
        batch_op.drop_column('current_date')

    # ### end Alembic commands ###
