"""empty message

Revision ID: 2ea2daf16ffd
Revises: 11f4f8befea2
Create Date: 2023-12-04 02:46:11.847053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea2daf16ffd'
down_revision = '11f4f8befea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.drop_constraint('employer_employer_phone_number_key', type_='unique')
        batch_op.drop_column('first_name')
        batch_op.drop_column('location')
        batch_op.drop_column('last_name')
        batch_op.drop_column('employer_phone_number')

    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('employer_phone_number', sa.Integer(), nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.create_unique_constraint(None, ['employer_phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('location',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('employer_phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_phone_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('employer_employer_phone_number_key', ['employer_phone_number'])

    # ### end Alembic commands ###
