"""empty message

Revision ID: 3df4a81a14d2
Revises: c0c38e1fc161
Create Date: 2023-12-11 02:42:49.939490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df4a81a14d2'
down_revision = 'c0c38e1fc161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userresume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userresume', schema=None) as batch_op:
        batch_op.drop_column('resume_name')

    # ### end Alembic commands ###
