"""empty message

Revision ID: 45070dc630cd
Revises: c3cdc29d94bf
Create Date: 2023-12-15 16:04:11.088619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45070dc630cd'
down_revision = 'c3cdc29d94bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userpreference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relocation_prefer_place', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userpreference', schema=None) as batch_op:
        batch_op.drop_column('relocation_prefer_place')

    # ### end Alembic commands ###
