"""empty message

Revision ID: 4b76cea407a7
Revises: 45070dc630cd
Create Date: 2023-12-17 03:43:04.210688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b76cea407a7'
down_revision = '45070dc630cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userpreference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relocation_place', sa.String(length=120), nullable=True))
        batch_op.drop_column('relocation_prefer_place')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userpreference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relocation_prefer_place', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('relocation_place')

    # ### end Alembic commands ###
