"""empty message

Revision ID: 5113c2288e39
Revises: ee2de4d4d8a7
Create Date: 2023-12-26 01:38:39.035397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5113c2288e39'
down_revision = 'ee2de4d4d8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.drop_column('company_logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_logo', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
