"""empty message

Revision ID: 5acca31a3154
Revises: 7b75d980bcba
Create Date: 2024-01-05 16:55:09.532010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acca31a3154'
down_revision = '7b75d980bcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userexperience', schema=None) as batch_op:
        batch_op.alter_column('startyear',
               existing_type=sa.DATE(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('endyear',
               existing_type=sa.DATE(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userexperience', schema=None) as batch_op:
        batch_op.alter_column('endyear',
               existing_type=sa.String(length=80),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('startyear',
               existing_type=sa.String(length=80),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
