"""empty message

Revision ID: 6322040e290a
Revises: a25173092a44
Create Date: 2023-12-18 04:02:21.281978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6322040e290a'
down_revision = 'a25173092a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userappliedjobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'employer', ['employer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userappliedjobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employer_id')

    # ### end Alembic commands ###
