"""empty message

Revision ID: 6824133fbbd0
Revises: 5e389fd1e7db
Create Date: 2024-02-03 05:32:20.010040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6824133fbbd0'
down_revision = '5e389fd1e7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['password'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
