"""empty message

Revision ID: 742d819b1da8
Revises: 6824133fbbd0
Create Date: 2024-02-03 05:39:13.079538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742d819b1da8'
down_revision = '6824133fbbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp', schema=None) as batch_op:
        batch_op.drop_constraint('temp_password_key', type_='unique')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('temp_password_key', ['password'])

    # ### end Alembic commands ###
