"""empty message

Revision ID: 7b75d980bcba
Revises: 
Create Date: 2024-01-05 05:44:48.573571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b75d980bcba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contacteduserprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postjobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('job_title', sa.String(length=500), nullable=True),
    sa.Column('company_email', sa.String(length=120), nullable=True),
    sa.Column('company_phone_number', sa.Integer(), nullable=True),
    sa.Column('number_hiring', sa.Integer(), nullable=True),
    sa.Column('work_location_type', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('job_type', sa.String(length=80), nullable=True),
    sa.Column('working_hours', sa.Integer(), nullable=True),
    sa.Column('experience_level_type', sa.String(length=80), nullable=True),
    sa.Column('education_degree', sa.String(length=80), nullable=True),
    sa.Column('min_experience', sa.Integer(), nullable=True),
    sa.Column('max_experience', sa.Integer(), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.Column('working_times', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('weekend_job', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('current_date', sa.Date(), nullable=True),
    sa.Column('current_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_email'),
    sa.UniqueConstraint('company_phone_number')
    )
    op.create_table('saveduserprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userbio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('usereducation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collage_name', sa.String(length=80), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Integer(), nullable=True),
    sa.Column('major', sa.String(length=80), nullable=True),
    sa.Column('degree', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userexperience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=80), nullable=True),
    sa.Column('company_name', sa.String(length=80), nullable=True),
    sa.Column('job_type', sa.String(length=80), nullable=True),
    sa.Column('startyear', sa.Date(), nullable=True),
    sa.Column('endyear', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userextradetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=40), nullable=True),
    sa.Column('disability', sa.String(length=40), nullable=True),
    sa.Column('work_authorization', sa.String(length=80), nullable=False),
    sa.Column('race', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userpreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title_preference', sa.String(length=500), nullable=True),
    sa.Column('full_time_job', sa.String(length=80), nullable=True),
    sa.Column('part_time_job', sa.String(length=80), nullable=True),
    sa.Column('contract_job', sa.String(length=80), nullable=True),
    sa.Column('temperory_job', sa.String(length=80), nullable=True),
    sa.Column('internship', sa.String(length=80), nullable=True),
    sa.Column('monday_to_friday', sa.String(length=80), nullable=True),
    sa.Column('weekend_as_needed', sa.String(length=80), nullable=True),
    sa.Column('weekend_only', sa.String(length=80), nullable=True),
    sa.Column('no_weekends', sa.String(length=80), nullable=True),
    sa.Column('holidays', sa.String(length=80), nullable=True),
    sa.Column('rotating_weekends', sa.String(length=80), nullable=True),
    sa.Column('weekdays', sa.String(length=80), nullable=True),
    sa.Column('every_weekend', sa.String(length=80), nullable=True),
    sa.Column('four_hour_shift', sa.String(length=80), nullable=True),
    sa.Column('eight_hour_shift', sa.String(length=80), nullable=True),
    sa.Column('ten_hour_shift', sa.String(length=80), nullable=True),
    sa.Column('twelve_hour_shift', sa.String(length=80), nullable=True),
    sa.Column('day_shift', sa.String(length=80), nullable=True),
    sa.Column('night_shift', sa.String(length=80), nullable=True),
    sa.Column('evening_shift', sa.String(length=80), nullable=True),
    sa.Column('no_night', sa.String(length=80), nullable=True),
    sa.Column('overnight_shift', sa.String(length=80), nullable=True),
    sa.Column('rotating_shift', sa.String(length=80), nullable=True),
    sa.Column('split_shift', sa.String(length=80), nullable=True),
    sa.Column('overtime', sa.String(length=80), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('salary_type', sa.String(length=80), nullable=True),
    sa.Column('relocation', sa.String(length=80), nullable=True),
    sa.Column('relocation_place', sa.String(length=120), nullable=True),
    sa.Column('remote_job', sa.String(length=80), nullable=True),
    sa.Column('hybrid_job', sa.String(length=80), nullable=True),
    sa.Column('in_person', sa.String(length=80), nullable=True),
    sa.Column('temperory_remote_job', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userresume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_resume', sa.LargeBinary(), nullable=True),
    sa.Column('resume_name', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userskills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=80), nullable=True),
    sa.Column('skill_year', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicantchat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=4000), nullable=False),
    sa.Column('current_date', sa.Date(), nullable=True),
    sa.Column('current_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['postjobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicantresume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_user_resume', sa.LargeBinary(), nullable=True),
    sa.Column('applicant_resume_name', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['postjobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['postjobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employerchat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=4000), nullable=False),
    sa.Column('current_date', sa.Date(), nullable=True),
    sa.Column('current_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['postjobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoriteapplicant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['postjobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userappliedjobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['postjobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersavedjobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['postjobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersavedjobs')
    op.drop_table('userappliedjobs')
    op.drop_table('favoriteapplicant')
    op.drop_table('employerchat')
    op.drop_table('applicants')
    op.drop_table('applicantresume')
    op.drop_table('applicantchat')
    op.drop_table('userskills')
    op.drop_table('userresume')
    op.drop_table('userpreference')
    op.drop_table('userextradetail')
    op.drop_table('userexperience')
    op.drop_table('usereducation')
    op.drop_table('userbio')
    op.drop_table('saveduserprofile')
    op.drop_table('postjobs')
    op.drop_table('contacteduserprofile')
    op.drop_table('user')
    op.drop_table('employer')
    # ### end Alembic commands ###
