"""empty message

Revision ID: 7e93bd850a22
Revises: e715dd025a96
Create Date: 2023-12-23 02:38:20.030877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e93bd850a22'
down_revision = 'e715dd025a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_resume', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('resume_name', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.drop_constraint('applicants_employer_id_fkey', type_='foreignkey')
        batch_op.drop_column('employer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('applicants_employer_id_fkey', 'employer', ['employer_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('resume_name')
        batch_op.drop_column('user_resume')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
