"""empty message

Revision ID: 97b90b9a7de2
Revises: 6322040e290a
Create Date: 2023-12-18 16:23:35.404148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b90b9a7de2'
down_revision = '6322040e290a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userappliedjobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userbio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'userbio', ['userbio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userappliedjobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('userbio_id')

    # ### end Alembic commands ###
