"""empty message

Revision ID: 9d510652c07a
Revises: 2c3857705504
Create Date: 2023-12-30 05:56:54.963081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d510652c07a'
down_revision = '2c3857705504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_degree', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.drop_column('education_degree')

    # ### end Alembic commands ###
