"""empty message

Revision ID: b497c1c6360b
Revises: 5acca31a3154
Create Date: 2024-01-05 19:20:12.528457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b497c1c6360b'
down_revision = '5acca31a3154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userexperience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_year', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('end_year', sa.String(length=80), nullable=True))
        batch_op.drop_column('startyear')
        batch_op.drop_column('endyear')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userexperience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endyear', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('startyear', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('end_year')
        batch_op.drop_column('start_year')

    # ### end Alembic commands ###
