"""empty message

Revision ID: c3cdc29d94bf
Revises: 61f0e6acb3b0
Create Date: 2023-12-15 16:01:19.660375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3cdc29d94bf'
down_revision = '61f0e6acb3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinternship')
    with op.batch_alter_table('userpreference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internship', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('monday_to_friday', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('weekend_as_needed', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('weekend_only', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('no_weekends', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('holidays', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('rotating_weekends', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('weekdays', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('every_weekend', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('four_hour_shift', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('eight_hour_shift', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('ten_hour_shift', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('twelve_hour_shift', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('day_shift', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('night_shift', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('evening_shift', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('no_night', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('overnight_shift', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('rotating_shift', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('split_shift', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('overtime', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('salary_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('in_person', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('temperory_remote_job', sa.String(length=80), nullable=True))
        batch_op.drop_column('night_shift_job')
        batch_op.drop_column('user_visibility_profile')
        batch_op.drop_column('permanent_job')
        batch_op.drop_column('onsite_job')
        batch_op.drop_column('day_shift_job')
        batch_op.drop_column('location_preference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userpreference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_preference', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('day_shift_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('onsite_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('permanent_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_visibility_profile', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('night_shift_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('temperory_remote_job')
        batch_op.drop_column('in_person')
        batch_op.drop_column('salary_type')
        batch_op.drop_column('overtime')
        batch_op.drop_column('split_shift')
        batch_op.drop_column('rotating_shift')
        batch_op.drop_column('overnight_shift')
        batch_op.drop_column('no_night')
        batch_op.drop_column('evening_shift')
        batch_op.drop_column('night_shift')
        batch_op.drop_column('day_shift')
        batch_op.drop_column('twelve_hour_shift')
        batch_op.drop_column('ten_hour_shift')
        batch_op.drop_column('eight_hour_shift')
        batch_op.drop_column('four_hour_shift')
        batch_op.drop_column('every_weekend')
        batch_op.drop_column('weekdays')
        batch_op.drop_column('rotating_weekends')
        batch_op.drop_column('holidays')
        batch_op.drop_column('no_weekends')
        batch_op.drop_column('weekend_only')
        batch_op.drop_column('weekend_as_needed')
        batch_op.drop_column('monday_to_friday')
        batch_op.drop_column('internship')

    op.create_table('userinternship',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('start_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=4000), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userinternship_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='userinternship_pkey')
    )
    # ### end Alembic commands ###
