"""empty message

Revision ID: c89f65e2343a
Revises: 08d4c7994c86
Create Date: 2023-12-23 18:29:44.514352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89f65e2343a'
down_revision = '08d4c7994c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_constraint('applicants_email_key', type_='unique')
        batch_op.drop_constraint('applicants_phone_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.create_unique_constraint('applicants_phone_number_key', ['phone_number'])
        batch_op.create_unique_constraint('applicants_email_key', ['email'])

    # ### end Alembic commands ###
