"""empty message

Revision ID: cf1ef900eccf
Revises: 9b9e4612fd26
Create Date: 2023-12-07 02:20:14.190411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1ef900eccf'
down_revision = '9b9e4612fd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_logo', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('company_size', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('number_hiring', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('work_location_type', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('job_type', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('working_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('experience_level_type', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('max_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_salary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weekend_job', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('benefits', sa.ARRAY(sa.String()), nullable=True))
        batch_op.alter_column('employer_phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('company_phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('min_experience',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('full_time_job')
        batch_op.drop_column('hybrid_job')
        batch_op.drop_column('contract_job')
        batch_op.drop_column('temperory_job')
        batch_op.drop_column('part_time_job')
        batch_op.drop_column('relocation')
        batch_op.drop_column('onsite_job')
        batch_op.drop_column('permanent_job')
        batch_op.drop_column('remote_job')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('permanent_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('onsite_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('relocation', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('part_time_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('temperory_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contract_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hybrid_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_time_job', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.alter_column('min_experience',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('company_phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('employer_phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('benefits')
        batch_op.drop_column('weekend_job')
        batch_op.drop_column('max_salary')
        batch_op.drop_column('max_experience')
        batch_op.drop_column('experience_level_type')
        batch_op.drop_column('working_hours')
        batch_op.drop_column('job_type')
        batch_op.drop_column('work_location_type')
        batch_op.drop_column('number_hiring')
        batch_op.drop_column('company_size')
        batch_op.drop_column('company_logo')

    # ### end Alembic commands ###
