"""empty message

Revision ID: d6ceaae1e56b
Revises: 4fe5af2909a7
Create Date: 2023-12-08 00:09:43.672822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6ceaae1e56b'
down_revision = '4fe5af2909a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.drop_column('benefits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefits', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
