"""empty message

Revision ID: e715dd025a96
Revises: 97b90b9a7de2
Create Date: 2023-12-18 21:13:14.114310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e715dd025a96'
down_revision = '97b90b9a7de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userappliedjobs', schema=None) as batch_op:
        batch_op.drop_constraint('userappliedjobs_userbio_id_fkey', type_='foreignkey')
        batch_op.drop_column('userbio_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userappliedjobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userbio_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('userappliedjobs_userbio_id_fkey', 'userbio', ['userbio_id'], ['id'])

    # ### end Alembic commands ###
