"""empty message

Revision ID: ee2de4d4d8a7
Revises: c89f65e2343a
Create Date: 2023-12-24 17:33:07.877558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2de4d4d8a7'
down_revision = 'c89f65e2343a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicantchat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=4000), nullable=False),
    sa.Column('current_date', sa.Date(), nullable=True),
    sa.Column('current_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['postjobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employerchat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=4000), nullable=False),
    sa.Column('current_date', sa.Date(), nullable=True),
    sa.Column('current_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['postjobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employerchat')
    op.drop_table('applicantchat')
    # ### end Alembic commands ###
