"""empty message

Revision ID: f0f0a0c6ae45
Revises: f46ae1bbf80f
Create Date: 2024-02-25 16:01:26.389192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f0a0c6ae45'
down_revision = 'f46ae1bbf80f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp')
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postjobs', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)

    op.create_table('temp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='temp_pkey'),
    sa.UniqueConstraint('email', name='temp_email_key')
    )
    # ### end Alembic commands ###
