"""empty message

Revision ID: f36b7b44fa52
Revises: d6ceaae1e56b
Create Date: 2023-12-09 12:33:34.823405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36b7b44fa52'
down_revision = 'd6ceaae1e56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userbio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=40), nullable=True),
    sa.Column('disability', sa.String(length=40), nullable=True),
    sa.Column('work_authorization', sa.String(length=80), nullable=False),
    sa.Column('race', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_phone_number_key', type_='unique')
        batch_op.drop_column('last_name')
        batch_op.drop_column('gender')
        batch_op.drop_column('disability')
        batch_op.drop_column('location')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('user_visibility_profile')
        batch_op.drop_column('work_authorization')
        batch_op.drop_column('first_name')
        batch_op.drop_column('race')
        batch_op.drop_column('language')

    with op.batch_alter_table('userpreference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_visibility_profile', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userpreference', schema=None) as batch_op:
        batch_op.drop_column('user_visibility_profile')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('race', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('work_authorization', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_visibility_profile', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('disability', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_phone_number_key', ['phone_number'])

    op.drop_table('userbio')
    # ### end Alembic commands ###
