name: CI-CD-FOR-DEV-BRANCH
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:  
      
      - name: Run a one-line script
        run: echo Hello, world!
       
