name: CI-CD-FOR-DEV-BRANCH
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:  
      
    - uses: actions/checkout@v3

    - run: npm install
    - run: npm install -g pm2
    - run: pm2 start "npm run start" --name "hiring"





        
       
