name: CI-CD-FOR-DEV-BRANCH
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:  
      
    - uses: actions/checkout@v3

    - run: npm install
    - run: sudo npm install -g pm2
    - run: npm install react-html-parser
    - run : npm install socket.io-client
    - run: cp env-develop .env 
    - run: pm2 restart hiring
    #- run: pm2 start "npm run start" --name "hiring"
    #pm2 start "cd /home/ubuntu/actions-runner/_work/job-board-shahsmit293/job-board-shahsmit293 && npm run start" --name "hiring"
    #sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu





        
       
