name: CI-CD-FOR-DEV-BRANCH
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:  
      
      - name: Access Dir
        run: |
          sudo su
          cd /home/ubuntu/hiring
          pwd


      - name: Git Update
        run: |
          git pull



        
       
